### ISSUE TITLE
Add ability to easily copy an emoji

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/emoj#2]
I'm thinking something like this (in the interactive prompt):

```
› unicorns
🦄  🎠  🐴  🌈  🐎  ✨  🍓
 1   2   3   4   5   6   7
```

And you can use for example <kbd>Ctrl</kbd>+<kbd>1</kbd> to copy the first emoji.

Need people's thoughts. Any way to better present / handle this?
The goal is to quickly be able to find and get a relevant emoji.

Should also have a `-c, --copy` flag for non-interactive mode.

**Comment by huyhong** [comment]
Something like this is useful for all the times I need to pull up an emoji:
https://github.com/huyhong/emoj/commit/3fbf802e4ccb6dd00ec0a5f65de2b0ec111bc51f

**Comment by radiovisual** [comment]
Yes, I think a combination of [keypress](https://www.npmjs.com/package/keypress) to listen for hotkeys like <kbd>Ctrl</kbd> + <kbd>1</kbd> and [copy-paste](https://www.npmjs.com/package/copy-paste) to get the value into the clipboard would be all you need to pull this off.

**Comment by sindresorhus** [comment]
Yeah, I know how to implement it. That's easy. Just looking for feedback on the UI and the interaction.

**Comment by vhmth** [comment]
+1

**Comment by zwacky** [comment]
I see myself copying the whole row just to pick out and keep the ones I like, not only 1. but it might just be me.

**Comment by sindresorhus** [comment]
@zwacky What if you could do for example <kbd>Ctrl</kbd>+<kbd>1</kbd>, <kbd>Ctrl</kbd>+<kbd>2</kbd> to copy multiple.

**Comment by zwacky** [comment]
could work if you keep holding down `ctrl` and press numbers to add them to the clipboard.
as soon as you press `ctrl` anew, the clipboard will start fresh.

not sure if this is super intuitive but a one liner could explain this pretty well.

**Comment by sindresorhus** [comment]
@zwacky Yeah, happy to consider other ways of doing it, but I don't think most would want 7 emojis copied to their clipboard and manually having to delete the ones they don't want.

**Comment by lukeed** [comment]
Would also like `command` + `click`.

I imagine the majority of people already have `command` + a number already bound... especially if they've left their terminal prompts with default settings.

**Comment by matchai** [comment]
I agree with @lukeed. Why not simply leave it as pressing the number to select that emoji?
Once the number key has been pressed, those emoji will be "selected" (maybe a color change for that number) and pressing enter will copy the selected emoji.

**Comment by lukeed** [comment]
@matchai Or a number(s) followed by native copy.

<kbd>1</kbd>, <kbd>2</kbd>, <kbd>5</kbd>, <kbd>CMD+C</kbd>

**Comment by vhmth** [comment]
I like @matchai's approach. That's good UX. You have a confirmation/guiding UI.

**Comment by radiovisual** [comment]
I don't like the approach of just pressing a number, seems pretty invasive. If I have something important in my clipboard, and then I go to search for the 💯  emoji, then my important clipboard data will be replaced by a random emoji, that would make me mad. I like the deliberate (intentional) approach of mapping a control key to the hotkey, like <kbd>CTRL</kbd> +  <kbd>1</kbd>....

**Comment by radiovisual** [comment]
Though, I may have misunderstood. If **"Once the number key has been pressed"*** actually means "Once the number printed to the terminal has been clicked", then I like this idea, but I would say that in this case, the numbers are not necessary. Simply clicking or double-clicking on the emoji character to copy the value into the clipboard would be cleaner.

**Comment by matchai** [comment]
@radiovisual I did not mean clicking on the emoji being selected. I'm personally not a fan of having a primary input method being a mouse-click on a CLI app. I do think it would be a great as an additional input method for those who like that UX.

I totally understand why you'd want to avoid using numbers for selections. I totally oversaw the use case where a user would be inputting numbers into their strings. I still don't think <kbd>CTRL</kbd> + <kbd>1</kbd> is the right answer though. <kbd>CTRL</kbd> + Number is commonly used as the default hotkey to select a window/tab in terminal apps.

What about using <kbd>RETURN</kbd> to toggle between "input mode" and "emoji selection mode"?

**Comment by radiovisual** [comment]
@matchai , yeah, I agree <kbd>CTRL</kbd> + Number might too common. As for the toggle switch, I think it could work for users who want to use the keyboard as the primary input, because it equals the same number of press events that can be used right now to select a single emoji character with the mouse:

**Terminal Mouse Selection**: <kbd>LMB</kbd> + <kbd>CMD</kbd> + <kbd>C</kbd> 
**"Toggle" Keyboard Selection**: <kbd>\<TOGGLE KEY\></kbd> + <kbd>\<NUMBER KEY\></kbd> + <kbd>\<TOGGLE KEY\></kbd> 

Also, I 100% agree that the primary input method for a CLI tool should be the keyboard, but I have to think about where and how I typically use emojis. I almost never use emojis in terminal applications. 99.8% of the time, I am going to paste them into a text editor, a web browser, or a chat application...and for that, the primary input device is the mouse, so having the mouse able to copy the emoji seems like a built-in shortcut to me. 

Personally, I think the idea of having both keyboard hotkeys and mouse-enabled interaction would be ideal. Each only involving a one or two-step process (i.e., 1 or 2 press events).

Namely:

1. **With Mouse:** Single-Click (or Double-Click) on the emoji to get it into the clipboard for users who intend to paste the emoji into a browser, editor or chat application, and,
2. **With Keyboard:** Offer a hotkey combo to allow a quick-copy of the emoji into the clipboard 

If the process takes 3 or more press events to get the emoji into the clipboard, then it's not worth adding in, since right now its only a three-step (three-event) process to copy the emoji using the mouse and native OS copy-paste methods.

**Comment by brock** [comment]
Throwing out another idea.

In the interactive prompt, you could press `Enter` or `Tab` to go into "arrow mode" like Yeoman does.

![yo](https://cloud.githubusercontent.com/assets/654725/16324311/c43da60e-3978-11e6-8db9-9f8bac537a51.gif)

**Comment by noodlesftw** [comment]
Didn't even see this issue, but I already made a pull request for copying the emojis to your clipboard. It copies the emojis when you press enter.

**Comment by radiovisual** [comment]
I am really liking @zwacky 's idea of holding down the <kbd>CTRL</kbd> key, which activates "selection mode" (then the numbers could appear below the emoji. keeping the UI nice and clean). As long as the <kbd>CTRL</kbd> key is held down, you can use the number keys to copy one, or multiple emojis to the clipboard. Releasing the <kbd>CTRL</kbd> key and pressing it again would start a new copy session. For those that want all 7 emojis copied at once, perhaps a single key could be assigned for that. @noodlesftw has assigned the <kbd>Return</kbd> key to do just that in PR #8

**Comment by sindresorhus** [comment]
I like @zwacky's idea too. Let's go with that.

@noodlesftw Would you be able to update your pull request?

> For those rare occasions where you would want all 7 emojis copied at once

`0` could mean `all`?

**Comment by radiovisual** [comment]
> `0` could mean `all`?

👍

**Comment by noodlesftw** [comment]
@sindresorhus I'll update it tomorrow night, haven't got the time to work on it this weekend. I'll hold on to @zwacky's idea.

**Comment by sindresorhus** [comment]
I've added a `-c, --copy` flag for non-interactive mode. I haven't had time yet to implement the interactive part. PR still welcome for that :)

**Comment by sindresorhus** [comment]
This is fixed in the latest version.
